import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Etnomedicine Finder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gradient-to-r from-cyan-500 to-blue-500">
        <div className="container ">
          <div className="pt-10">
            <h1 className="text-5xl text-center">ETNOMEDICINE FINDER</h1>
          </div>
          <div>
            <p className="text-2xl text-center pt-10">Temukan Solusi dari penyakitmu disini!</p>
          </div>
          <div className="text-center pt-40 pb-20">
            <form action="">
              <input className="rounded-lg bg-black" type="search" />
              <button className="">Cari</button>
            </form>
          </div>
          <div className="table w-full border-separate border border-spacing-3 table-auto">
            <div className="table-header-group">
              <div className="table-row">
                <div className="table-cell text-center border">No</div>
                <div className="table-cell text-center border">Bagian yang Dimanfaatkan</div>
                <div className="table-cell text-center border">Nama Lokal</div>
                <div className="table-cell text-center border">Nama Ilmiah</div>
                <div className="table-cell text-center border">Wilayah</div>
                <div className="table-cell text-center border">Jenis Ramuan U/ Penyakit</div>
                <div className="table-cell text-center border">Resep</div>
              </div>
            </div>
            <div className="table-row-group">
              <div className="table-row">
                <div className="table-cell text-center">@</div>
                <div className="table-cell text-center">@</div>
                <div className="table-cell text-center">@</div>
                <div className="table-cell text-center">@</div>
                <div className="table-cell text-center">@</div>
                <div className="table-cell text-center">@</div>
                <div className="table-cell text-center">@</div>
              </div>
            </div>
          </div>
          <div className="py-10">*Tugas Kelompok</div>
        </div>
      </main>
    </>
  );
}
