import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import { devNull } from 'os';

const inter = Inter({ subsets: ['latin'] });

interface MedicData {
  id: number,
  herb_name: string,
  parts_used: string,
  origin_loc: string,
  scientific_name: string
  disease: string
  recipe: string
}

export default function Home() {
  const router = useRouter()
  const [disease, setDisease] = useState('')
 
  async function handleSubmit(data: string) {
    console.log(data);
    router.push(`/search?disease=${data}`);
  }

  return (
    <>
      <Head>
        <title>Etnomedicine Finder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gradient-to-r from-cyan-500 to-blue-500">
        <div className="container ">
          <div className="pt-10">
            <h1 className="text-5xl text-center">ETNOMEDICINE FINDER</h1>
          </div>
          <div>
            <p className="text-2xl text-center pt-10">Temukan Solusi dari Penyakitmu di Sini!</p>
          </div>
          <div className="text-center pt-40 pb-20">
            <form onSubmit={e => {
              e.preventDefault()
              handleSubmit(disease)
            }}>
              <input
                className="rounded-lg mx-2 bg-black"
                type="search"
                value={disease}
                onChange={e => {  
                  e.preventDefault
                  setDisease(e.target.value)
                }}
              />
              <button className="" type='submit'>Cari</button>
            </form>
          </div>
          
          {/* {oneMedicine?.id ? (
            <div>
              <h1>{oneMedicine.herb_name}</h1>
            </div>
          ): null} */}

          <div className="table w-full border-separate border border-spacing-3 table-auto">
            <div className="table-header-group">
              <div className="table-row" >
                <div className="table-cell text-center ">No</div>
                <div className="table-cell text-center ">Bagian yang Dimanfaatkan</div>
                <div className="table-cell text-center ">Nama Lokal</div>
                <div className="table-cell text-center ">Nama Ilmiah</div>
                <div className="table-cell text-center ">Wilayah</div>
                <div className="table-cell text-center ">Jenis Ramuan Untuk Penyakit</div>
                <div className="table-cell text-center ">Resep</div>
              </div>
            </div>

            <div className="table-row-group">

              {/* Display Data Dummy
              {medicines.map(medic => (
                <div className="table-row" key={medic.id} onClick={() => appendQuery(medic.id)}>
                  <div className="table-cell text-center">{medic.id}</div>
                  <div className="table-cell text-center">{medic.parts_used}</div>
                  <div className="table-cell text-center">{medic.herb_name}</div>
                  <div className="table-cell text-center">{medic.scientific_name}</div>
                  <div className="table-cell text-center">{medic.origin_loc}</div>
                  <div className="table-cell text-center">{medic.disease}</div>
                  <div className="table-cell text-center">{medic.recipe}</div>
                </div>
              ))} */}
            </div>
            {/* <div className="table-row-group">
                  <div className="table-row">
                    <div className="table-cell text-center">@</div>
                    <div className="table-cell text-center">@</div>
                    <div className="table-cell text-center">@</div>
                    <div className="table-cell text-center">@</div>
                    <div className="table-cell text-center">@</div>
                    <div className="table-cell text-center">@</div>
                    <div className="table-cell text-center">@</div>
                  </div>
            </div>
             */}
          </div>

          <div className="py-10">*Tugas Kelompok</div>
        </div>
      </main>
    </>
  );
}
