import Head from 'next/head';
import { Inter } from '@next/font/google';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import { devNull } from 'os';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const router = useRouter()
  const [disease, setDisease] = useState('')

  async function handleSubmit(data: string) {
    console.log(data);
    router.push(`/search/${data}`);
  }

  return (
    <>
      <Head>
        <title>Etnomedicine Finder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gradient-to-r from-cyan-500 to-blue-500">
        <div className="container ">
          <div className="pt-10">
            <h1 className="text-5xl text-center">ETNOMEDICINE FINDER</h1>
          </div>
          <div>
            <p className="text-2xl text-center pt-20">Temukan Solusi dari penyakitmu disini!</p>
          </div>
          <div className="text-center pt-40 pb-20">
            <form onSubmit={e => {
              e.preventDefault()
              handleSubmit(disease)
            }}>
              <input
                className="rounded-lg mx-2 bg-black"
                type="search"
                value={disease}
                onChange={e => {
                  e.preventDefault
                  setDisease(e.target.value)
                }}
              />
              <button className="" type='submit'>Cari</button>
            </form>
          </div>

          <div className="py-10">*Tugas Kelompok</div>
        </div>
      </main>
    </>
  );
}
